### PR TITLE
typos

### PR DESCRIPTION
**Pull request by njt**
let's see if I can drive this newfangled technology

are these types of fixes helpful to you?

### CODE REVIEW

**Comment by tanyagray** [comment]
Yes. There will be a million billion typos most likely. Probably even whole sentences which make no sense. Heh.

**Comment by njt** [comment]
Do you want me to batch them or make a PR for each file?  (I figure you want them batched, but have been playing it safe)

**Comment by njt** [comment]
(and what should I do when there are missing files, eg there's a link to coursebook/modules/project-management/independent-charter but it doesn't even exist as a blank file.  Lodge an issue?

**Comment by tanyagray** [comment]
Batching is a bit difficult unless you get into branching which is a pain, so batches are fine :)

**Comment by tanyagray** [comment]
Missing files as issues would be ace.

**Pull request merged**
